### ISSUE TITLE
lezioni: "prossima lezione" does not send correct link

### ISSUE THREAD

**Issue by Deco71** [appinfosapienza/UniBotJS#16]

**Comment by Shoenen** [comment]
### The problem description since Deco is a quaquaraqua:

When you pass "next" to function `onTime(...)` it will return true on the first lecture (in the `lezioni.json`) than will satisfy this condition:
`mode === "next" && shortDay.toUpperCase() === doWShort && currentHH >= 8 && start > currentHH && currentHH <= 19`.
The correct behavior should be that it will search the lecture which is the earliest given a certain hour. 
For example at 9am of monday, it should give the lecture at 10am as the next lession even if it is listed as the last lecture in the .json file, instead than a lecture at 1pm but listed as first lecture in the .json

**Comment by dag7dev** [comment]
Could it be a good idea to:
- look for all the occurrences
- take and return the minimum course with the lowest hour
?
